# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-03 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='view_conut',
            new_name='view_count',
        ),
    ]
